function footer(){
    return '<div></div><img src="'+$.image()+'/common/footer.png" alt="" />';
}
function gnbView(){
    return '   <div>'
    +'      <div>'
    +'         <ul>'
    +'            <li><a id="ticketing" href="${context}/reservation/main">예매</a></li>'
    +'            <li><a id="movie" href="#">영화</a></li>'
    +'            <li><a id="multiplex" href="${context}/multiplex/main">영화관</a></li>'
    +'            <li><a class="abb1_tooltip" href="#">스위트샵<span>미구현</span></a></li>'
    +'            <li><a class="abb1_tooltip" href="#">이벤트<span>미구현</span></a></li>'
    +'            <li><a class="abb1_tooltip" href="#">기프트샵<span>미구현</span></a></li>'
    +'         </ul>'
    +'      </div>'
    +'   </div>';
}
function headerView(){
    return '<div class="abb1_no_padding abb1_width_100 abb1_text_center">'
    +'      <div style="margin: 0 auto;">'
    +'         <a href="/web"><img src="'+$.image()+'/common/main_logo.png" alt=""/></a>'
    +'      </div>'
    +'   </div>'
    +'   <nav id="boot-nav" class="abb1_navbar abb1_navbar-default">'
    +'      <div class="abb1_navbar_container">'
    +'         <div class="navbar-header">'
    +'            <a id="brand" class="navbar-brand" href="https://www.facebook.com/LotteCinema.kr"><span class="abb1_facebook"><img src="'+$.image()+'/common/facebook.png" alt="" width="25px" height="25px"/> 롯데시네마 페이스북</span></a>'
    +'         </div>'
    +'         <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">'
    +'            <ul id="ul_gnb" class="nav navbar-nav navbar-right">'
    +'               <li><a id="login" href="${context}/customer/login">로그인<span class="sr-only">(current)</span></a></li>'
    +'               <li><a id="register" href="${context}/customer/signUp">회원가입<span class="sr-only">(current)</span></a></li>'
    +'               <li><a id="FAQ" href="${context}/board/main">고객센터<span class="sr-only">(current)</span></a></li>'
    +'            </ul>'
    +'         </div>'
    +'      </div>'
    +'   </nav>';
}
function headerLoginView(){
    return '<div class="abb1_no_padding abb1_width_100 abb1_text_center">'
    +'   <div style="margin: 0 auto;">'
    +'      <a href="/web"><img src="'+$.image()+'/common/main_logo.png" alt=""/></a>'
    +'   </div>'
    +'</div>'
    +'<nav id="boot-nav" class="abb1_navbar abb1_navbar-default">'
    +'   <div class="abb1_navbar_container">'
    +'      <div class="navbar-header">'
    +'         <a id="brand" class="navbar-brand" href="https://www.facebook.com/LotteCinema.kr"><span class="abb1_facebook"><img src="'+$.image()+'/common/facebook.png" alt="" width="25px" height="25px"/> 롯데시네마 페이스북</span></a>'
    +'      </div>'
    +'      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">'
    +'         <ul class="nav navbar-nav navbar-right">'
    +'            <li><a id="login" href="${context}/customer/login">로그인<span class="sr-only">(current)</span></a></li>'
    +'            <li><a id="register" href="#">회원가입<span class="sr-only">(current)</span></a></li>'
    +'            <li><a id="FAQ" href="#">고객센터<span class="sr-only">(current)</span></a></li>'
    +'         </ul>'
    +'      </div>'
    +'   </div>'
    +'</nav>';
}
function adminLoginView(){
    return '<div id="signupSuccess">'
	+'		<div id="signup_success">'
    	+'			<div>'
    	+'				<table>'
    	+'		         <tr>'
    	+'		         	<td>'
    	+'			         	<h3><strong>관리자</strong><span>님 환영합니다!</span></h3>'
    	+'		         	</td>'
    	+'		         </tr>'
    	+'		         <tr>'
    	+'			         <td>'
    	+'			         <ul>'
    	+'						 <li>'
    	+'							<a href="${context}/admin/index"><input type="button" value="관리자 페이지 GO"/></a>'
    	+'						 </li>'
    	+'					 </ul>'
    	+'					 </td>'
    	+'		         </tr>'
    	+'		      	</table>'
    	+'			</div>'
    	+'		</div>'
    	+'	</div>';
}
function adminIndexView(){
    return '<div id="page-wrapper">'
	+'            <div class="container-fluid">'
	+'                <div class="row">'
	+'                    <div class="col-lg-12">'
	+'                        <h1 class="page-header">'
	+'                            Dashboard <small>Statistics Overview</small>'
	+'                        </h1>'
	+'                        <ol class="breadcrumb">'
	+'                            <li class="active">'
	+'                                <i class="fa fa-dashboard"></i> Dashboard'
	+'                            </li>'
	+'                        </ol>'
	+'                    </div>'
	+'                </div>'
	+'                <div class="row">'
	+'                    <div class="col-lg-12">'
	+'                        <div class="alert alert-info alert-dismissable">'
	+'                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>'
	+'                            <i class="fa fa-info-circle"></i>  <strong>Like SB Admin?</strong> Try out <a href="http://startbootstrap.com/template-overviews/sb-admin-2" class="alert-link">SB Admin 2</a> for additional features!'
	+'                        </div>'
	+'                    </div>'
	+'                </div>'
	+'                <div class="row">'
	+'                    <div class="col-lg-3 col-md-6">'
	+'                        <div class="panel panel-primary">'
	+'                            <div class="panel-heading">'
	+'                                <div class="row">'
	+'                                    <div class="col-xs-3">'
	+'                                        <i class="fa fa-shopping-cart fa-5x"></i>'
	+'                                    </div>'
	+'                                    <div class="col-xs-9 text-right">'
	+'                                        <div class="huge">26</div>'
	+'                                        <div>오늘 예매 수</div>'
	+'                                    </div>'
	+'                                </div>'
	+'                            </div>'
	+'                            <a href="#">'
	+'                                <div class="panel-footer">'
	+'                                    <span class="pull-left">View Details</span>'
	+'                                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>'
	+'                                    <div class="clearfix"></div>'
	+'                                </div>'
	+'                            </a>'
	+'                        </div>'
	+'                    </div>'
	+'                    <div class="col-lg-3 col-md-6">'
	+'                        <div class="panel panel-green">'
	+'                            <div class="panel-heading">'
	+'                                <div class="row">'
	+'                                    <div class="col-xs-3">'
	+'                                        <i class="fa fa-tasks fa-5x"></i>'
	+'                                    </div>'
	+'                                    <div class="col-xs-9 text-right">'
	+'                                        <div class="huge">12</div>'
	+'                                        <div>등록 영화관 수</div>'
	+'                                    </div>'
	+'                                </div>'
	+'                            </div>'
	+'                            <a href="#">'
	+'                                <div class="panel-footer">'
	+'                                    <span class="pull-left">View Details</span>'
	+'                                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>'
	+'                                    <div class="clearfix"></div>'
	+'                                </div>'
	+'                            </a>'
	+'                        </div>'
	+'                    </div>'
	+'                    <div class="col-lg-3 col-md-6">'
	+'                        <div class="panel panel-yellow">'
	+'                            <div class="panel-heading">'
	+'                                <div class="row">'
	+'                                    <div class="col-xs-3">'
	+'                                        <i class="fa fa-support fa-5x"></i>'
	+'                                    </div>'
	+'                                    <div class="col-xs-9 text-right">'
	+'                                        <div class="huge">124</div>'
	+'                                        <div>등록 영화 수</div>'
	+'                                    </div>'
	+'                                </div>'
	+'                            </div>'
	+'                            <a href="#">'
	+'                                <div class="panel-footer">'
	+'                                    <span class="pull-left">View Details</span>'
	+'                                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>'
	+'                                    <div class="clearfix"></div>'
	+'                                </div>'
	+'                            </a>'
	+'                        </div>'
	+'                    </div>'
	+'                    <div class="col-lg-3 col-md-6">'
	+'                        <div class="panel panel-red">'
	+'                            <div class="panel-heading">'
	+'                                <div class="row">'
	+'                                    <div class="col-xs-3">'
	+'                                        <i class="fa fa-comments fa-5x"></i>'
	+'                                    </div>'
	+'                                    <div class="col-xs-9 text-right">'
	+'                                        <div class="huge">13</div>'
	+'                                        <div>당일 업데이트 게시글 수</div>'
	+'                                    </div>'
	+'                                </div>'
	+'                            </div>'
	+'                            <a href="#">'
	+'                                <div class="panel-footer">'
	+'                                    <span class="pull-left">View Details</span>'
	+'                                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>'
	+'                                    <div class="clearfix"></div>'
	+'                                </div>'
	+'                            </a>'
	+'                        </div>'
	+'                    </div>'
	+'                </div>'
	+'                <div class="row">'
	+'                    <div class="col-lg-12">'
	+'                         <div id="area_chart"></div>'
	+'                    </div>'
	+'                </div>'
	+'                <div class="row">'
	+'                    <div class="col-lg-12">'
	+'                       	<div id="donut_chart"></div>'
	+'                    </div>'
	+'                </div>'
	+'            </div>'
	+'        </div>';
}
function adminStatisticView(){
    return '<div id="page-wrapper">'
	+'			<div id="statistic">'
	+'				<select name="" id="statistic_category">'
	+'					<option selected>카테고리 선택</option>'
	+'					<option value="multiplex">영화관</option>'
	+'					<option value="movie">영화</option>'
	+'				</select>'
	+'				<input id="statistic_search_keyword" type="text"/>'
	+'				<input id="statistic_search_btn" type="button" value="검색"/>'
	+'			</div>'
	+'		</div>'
	+'        </div>';
}
function adminStatisticChartView(){
    return '<div id="page-wrapper"><div id="admin_movie_donut_chart"></div></div>';
}
function adminMovieRegisterView(){
    return '<div id="page-wrapper">'
	+'    <div id="movie_register">'
	+'	<div>영화 등록</div>'
	+'	<div>'
	+'		<div id="movie_register_table">'
	+'		<table>'
	+'			<tr>'
	+'				<td>영화명</td>'
	+'				<td><input id="" type="text"/></td>'
	+'			</tr>'
	+'			<tr>'
	+'				<td>등급</td>'
	+'				<td><input id="" type="text"/></td>'
	+'			</tr>'
	+'			<tr>'
	+'				<td>개봉일</td>'
	+'				<td><input id="" type="text"/></td>'
	+'			</tr>'
	+'			<tr>'
	+'				<td>기본정보</td>'
	+'				<td><input id="" type="text"/></td>'
	+'			</tr>'
	+'			<tr>'
	+'				<td>시놉시스</td>'
	+'				<td><textarea name="" id="" cols="30" rows="6"></textarea></td>'
	+'			</tr>'
	+'			<tr>'
	+'				<td>감독 이름</td>'
	+'				<td><input id="" type="text"/></td>'
	+'			</tr>'
	+'			<tr>'
	+'				<td>감독 사진</td>'
	+'				<td><input type="file" /></td>'
	+'			</tr>'
	+'			<tr>'
	+'				<td>배우 이름</td>'
	+'				<td><input id="" type="text"/></td>'
	+'			</tr>'
	+'			<tr>'
	+'				<td>배우 사진</td>'
	+'				<td><input type="file" /></td>'
	+'			</tr>'
	+'			<tr>'
	+'				<td>영화 프로필 사진</td>'
	+'				<td><input type="file" /></td>'
	+'			</tr>'
	+'			<tr>'
	+'				<td>트레일러 URL</td>'
	+'				<td><span><input type="text"/></span></td>'
	+'			</tr>'
	+'			<tr id="trailer_check">'
	+'				<td><input id="" type="checkbox"/></td>'
	+'				<td>메인 페이지 트레일러로 등록</td>'
	+'			</tr>'
	+'		</table>'
	+'		</div>'
	+'		<div id="movie_register_btns">'
	+'			<input id="cancel" type="button" value="취소"/>'
	+'			<input id="confirm" type="button" value="확인"/>'
	+'		</div>'
	+'	</div>'
	+'</div>'
	+'</div>';
}
function adminCustomerView(){
    return '<div id="page-wrapper">'
    +'			<div id="customer">'
    +'				<div>회원 관리</div>'
    +'					<div id="customer_management_wrapper">'
    +'						<div>'
    +'							<input id="customer_search_keyword" type="text" placeholder="아이디 or 이름" />'
    +'							<input id="customer_search_btn" type="button" value="검색"/>'
    +'						</div>'
    +'						<div id="result">'
    +'							<div id="admin_customer_table">'
    +'								<table>'
    +'								<colgroup>'
    +'									<col />'
    +'									<col />'
    +'									<col />'
    +'									<col />'
    +'									<col />'
    +'								</colgroup>'
    +'								<thead>'
    +'									<tr>'
    +'									<th>ID</th>'
    +'									<th>이름</th>'
    +'									<th>성별</th>'
    +'									<th>생년월일</th>'
    +'									<th>삭제</th>'
    +'									</tr>'
    +'								</thead>'
    +'								<tbody>'
    +'									<tr>'
    +'										<td><a id="customer_id" href="#">abccd</a></td>'
    +'										<td><a id="customer_name" href="#">박준용</a></td>'
    +'										<td>남</td>'
    +'										<td>1990-05-18</td>'
    +'										<td><input id="delete" type="button" value="x"/></td>'
    +'									</tr>'
    +'								</tbody>'
    +'							</table>'
    +'						</div>'
    +'					</div>'
    +'				</div>'
    +'			</div>'
     +'       </div>';
}
function adminCustomerResultView(){
    return '<div id="customer_result">'
    +'	<table>'
    +'		<tr>'
    +'			<td>아이디</td>'
    +'			<td><input type="text" value="abccd"/></td>'
    +'		</tr>'
    +'		<tr>'
    +'			<td>비밀번호</td>'
    +'			<td><input type="password" value="abccd"/></td>'
    +'		</tr>'
    +'		<tr>'
    +'			<td>이름</td>'
    +'			<td><input type="text" value="박준용"/></td>'
    +'		</tr>'
    +'		<tr>'
    +'			<td>생년월일</td>'
    +'			<td><input type="text" value="19900518"/></td>'
    +'		</tr>'
    +'		<tr>'
    +'			<td>전화번호</td>'
    +'			<td><input type="text" value="010-2206-8900"/></td>'
    +'		</tr>'
    +'		<tr>'
    +'			<td>성별</td>'
    +'			<td><input type="text" value="M"/></td>'
    +'		</tr>'
    +'		<tr>'
    +'			<td>우편번호</td>'
    +'			<td><input type="text" value="01175"/></td>'
    +'		</tr>'
    +'		<tr>'
    +'			<td>상세주소</td>'
    +'			<td><input type="text" value="710호"/></td>'
    +'		</tr>'
    +'		<tr>'
    +'			<td>이메일</td>'
    +'			<td><input type="text" value="babungv@gmail.com"/></td>'
    +'		</tr>'
    +'		<tr>'
    +'			<td colspan="2"><input type="button" value="저장"/></td>'
    +'		</tr>'
    +'	</table>'
    +'	</div>';
}
function adminReservationView(){
    return '<div id="page-wrapper">'
    +'		<div id="reservation">'
    +'			<div>'
    +'				<select name="" id="reservation_category">'
    +'					<option selected>카테고리 선택</option>'
    +'					<option value="multiplex">영화관</option>'
    +'					<option value="movie">영화</option>'
    +'				</select>'
    +'				<input id="reservation_search_keyword" type="text" />'
    +'				<input id="reservation_search_btn" type="button" value="검색"/>'
    +'			</div></div></div>';
}
function adminReservationResultView(){
    return '<div id="page-wrapper">'
    +'		<div id="reservation">'
    +'			<div>'
    +'				<select name="" id="reservation_category">'
    +'					<option selected>카테고리 선택</option>'
    +'					<option value="multiplex">영화관</option>'
    +'					<option value="movie">영화</option>'
    +'				</select>'
    +'				<input id="reservation_search_keyword" type="text" />'
    +'				<input id="reservation_search_btn" type="button" value="검색"/>'
    +'			</div>'
    +'			<div>'
    +'				<div id="admin_reservation_list">'
    +'					<div>예매내역</div>'
    +'					<div>'
    +'					<table id="reservation_table">'
    +'						<colgroup>'
    +'							<col />'
    +'							<col />'
    +'							<col />'
    +'							<col />'
    +'							<col />'
    +'							<col />'
    +'				      	</colgroup>'
    +'				      	<thead>'
    +'							<tr>'
    +'								<th>관</th>'
    +'								<th>영화제목</th>'
    +'								<th>시작시간</th>'
    +'								<th>좌석번호</th>'
    +'								<th>예매날짜</th>'
    +'								<th>가격</th>'
    +'							</tr>'
    +'				   	   	</thead>'
    +'				     	<tbody>'
    +'							<tr>'
    +'								<td>1관</td>'
    +'								<td>아빠와 딸</td>'
    +'								<td>12:00</td>'
    +'								<td>A1</td>'
    +'								<td>2017-05-01</td>'
    +'								<td>10,000</td>'
    +'							</tr>'
    +'		   			   </tbody>'
    +'					</table>'
    +'					</div>'
    +'				</div>'
    +'				<div id="admin_cancel_list">'
    +'					<div>취소내역</div>'
    +'					<div>'
    +'					<table id="cancel_list_table">'
    +'						<colgroup>'
    +'							<col />'
    +'							<col />'
    +'							<col />'
    +'							<col />'
    +'							<col />'
    +'							<col />'
    +'				      	</colgroup>'
    +'				      	<thead>'
    +'							<tr>'
    +'								<th>관</th>'
    +'								<th>영화제목</th>'
    +'								<th>시작시간</th>'
    +'								<th>좌석번호</th>'
    +'								<th>예매날짜</th>'
    +'								<th>가격</th>'
    +'							</tr>'
    +'				      </thead>'
    +'				      <tbody>'
    +'							<tr>'
    +'								<td>1관</td>'
    +'								<td>아빠와 딸</td>'
    +'								<td>12:00</td>'
    +'								<td>A1</td>'
    +'								<td>2017-05-01</td>'
    +'								<td>10,000</td>'
    +'							</tr>'
    +'		   			   </tbody>'
    +'					</table>'
    +'					</div>'
    +'				</div>'
    +'				<div id="admin_movie_list">'
    +'					<div>영화검색</div>'
    +'					<div>'
    +'						<table id="movie_list_table">'
    +'							<colgroup>'
    +'								<col />'
    +'								<col />'
    +'								<col />'
    +'								<col />'
    +'								<col />'
    +'					      	</colgroup>'
    +'					      	<thead>'
    +'								<tr>'
    +'									<th>영화관</th>'
    +'									<th>상영관</th>'
    +'									<th>시작시간</th>'
    +'									<th>예매날짜</th>'
    +'									<th>가격</th>'
    +'								</tr>'
    +'					      	</thead>'
    +'					      	<tbody>'
    +'								<tr>'
    +'									<td>1관</td>'
    +'									<td>아빠와 딸</td>'
    +'									<td>12:00</td>'
    +'									<td>2017-05-01</td>'
    +'									<td>10,000</td>'
    +'								</tr>'
    +'			   			   </tbody>'
    +'						</table>'
    +'					</div>'
    +'				</div>'
    +'				<div id="admin_movie_donut_chart">'
    +'				</div>'
    +'			</div>'
    +'		</div>'
    +'    </div>';
}
function adminMovieManagementView(){
    return '<div id="page-wrapper">'
    +'        <div id="movie_management">'
    +'	        <div>영화 관리</div>'
    +'			<div id="management">'
    +'				<input id="movie_search_keyword" type="text" placeholder="영화명 입력" />'
    +'				<input id="movie_search_btn" type="button" value="검색"/>'
    +'			</div>'
    +'	        </div>'
    +'        </div>';
}
function adminMovieManagementTableView(){
    return '<div>'
	+'<div id="movie_management_table">'
	+'<table>'
	+'	<tr>'
	+'		<td rowspan="11"><img src="'+$.image()+'/movie/movie_poster_0.png" alt="" width="100%" height="100%"/></td>'
	+'		<td>영화명</td>'
	+'		<td><input id="" type="text" value="영화명"/></td>'
	+'	</tr>'
	+'	<tr>'
	+'		<td>등급</td>'
	+'		<td><input id="" type="text" value="등급"/></td>'
	+'	</tr>'
	+'	<tr>'
	+'		<td>개봉일</td>'
	+'		<td><input id="" type="text" value="개봉일"/></td>'
	+'	</tr>'
	+'	<tr>'
	+'		<td>기본정보</td>'
	+'		<td><input id="" type="text" value="기본정보"/></td>'
	+'	</tr>'
	+'	<tr>'
	+'		<td>시놉시스</td>'
	+'		<td><textarea name="" id="" cols="30" rows="6"></textarea></td>'
	+'	</tr>'
	+'	<tr>'
	+'		<td>감독 이름</td>'
	+'		<td><input id="" type="text" value="감독 이름"/></td>'
	+'	</tr>'
	+'	<tr>'
	+'		<td>감독 사진</td>'
	+'		<td><input type="file" /></td>'
	+'	</tr>'
	+'	<tr>'
	+'		<td>배우 이름</td>'
	+'		<td><input id="" type="text" value="배우 이름"/></td>'
	+'	</tr>'
	+'	<tr>'
	+'		<td>배우 사진</td>'
	+'		<td><input type="file" /></td>'
	+'	</tr>'
	+'	<tr>'
	+'		<td>영화 프로필 사진</td>'
	+'		<td><input type="file" /></td>'
	+'	</tr>'
	+'	<tr>'
	+'		<td>트레일러 URL</td>'
	+'		<td><input type="text" value="http://youtube.com/"/></td>'
	+'	</tr>'
	+'</table>'
	+'</div>'
	+'<div id="movie_management_btns">'
	+'	<input id="delete" type="button" value="삭제"/>'
	+'	<input id="update" type="button" value="수정"/>'
	+'</div>'
	+'</div>';
}
function adminBbsNoticeView(){
    return '<div id="page-wrapper">'
    +'		<div id="notice_table">'
    +'		<div>공지글 관리</div>'
    +'		<div id="notice_write_wrapper">'
    +'		<div>'
    +'			<input id="write" type="button" value="등록" />'
    +'		</div>'
    +'		<table>'
    +'			<colgroup>'
    +'				<col />'
    +'				<col />'
    +'				<col />'
    +'				<col />'
    +'			</colgroup>'
    +'			<tr>'
    +'				<th>순번</th>'
    +'				<th>제목</th>'
    +'				<th>작성시간</th>'
    +'				<th>삭제</th>'
    +'			</tr>'
    +'			<tr>'
    +'				<td>4</td>'
    +'				<td><a id="notice4" href="#">개인정보 보호내역</a></td>'
    +'				<td>2017-05-02</td>'
    +'				<td><input type="button" value="x"/></td>'
    +'			</tr>'
    +'			<tr>'
    +'			<td>3</td>'
    +'				<td><a href="#">개인정보 보호내역</a></td>'
    +'				<td>2017-05-02</td>'
    +'				<td><input type="button" value="x"/></td>'
    +'			</tr>'
    +'			<tr>'
    +'			<td>2</td>'
    +'				<td><a href="#">개인정보 보호내역</a></td>'
    +'				<td>2017-05-02</td>'
    +'				<td><input type="button" value="x"/></td>'
    +'			</tr>'
    +'			<tr>'
    +'			<td>1</td>'
    +'				<td><a href="#">개인정보 보호내역</a></td>'
    +'				<td>2017-05-02</td>'
    +'				<td><input type="button" value="x"/></td>'
    +'			</tr>'
    +'		</table>'
    +'		<div id="notice_pagination">'
    +'		   <table>'
    +'		      <tr>'
    +'		         <td>'
    +'		            <a href="#"><img src="'+$.image()+'/pagination/prev_all.gif" alt="" /></a>'
    +'		            <a href="#"><img src="'+$.image()+'/pagination/prev.gif" alt="" /></a>'
    +'		         </td>'
    +'		         <td>'
    +'		            <h4>'
    +'		            <a href="#">1</a>'
    +'		            <a href="#">2</a>'
    +'		            <a href="#">3</a>'
    +'		            <a href="#">4</a>'
    +'		            <a href="#">5</a>'
    +'		            <a href="#">6</a>'
    +'		            <a href="#">7</a>'
    +'		            <a href="#">8</a>'
    +'		            <a href="#">9</a>'
    +'		            <a href="#">10</a>'
    +'		            </h4>'
    +'		         </td>'
    +'		         <td>'
    +'		            <a href="#"><img src="'+$.image()+'/pagination/next.gif" alt="" /></a>'
    +'		            <a href="#"><img src="'+$.image()+'/pagination/next_all.gif" alt="" /></a>'
    +'		         </td>'
    +'		      </tr>'
    +'		   </table>'
    +'		  </div>'
    +'		</div>'
    +'	</div>';
    +'        </div>';
}
function adminBbsNoticeWriteView(){
    return '<div id="notice_write">'
	+'	<table>'
	+'      <colgroup>'
	+'	      <col />'
	+'	      <col />'
	+'      </colgroup>'
	+'         <tr>'
	+'            <td>제목</td>'
	+'            <td>'
	+'           	 <input id="notice_title" type="text" name="title" maxlength="50"/>'
	+'            </td>'
	+'         </tr>'
	+'         <tr>'
	+'            <td>내용</td>'
	+'            <td>'
	+'               <textarea name="contents" id="bbs_write_notice" cols="30" rows="10"></textarea>'
	+'            </td>'
	+'         </tr>'
	+'         <tr>'
	+'            <td>첨부파일</td>'
	+'            <td>'
	+'               <input type="file" id="file" name="file" value="파일 찾기"/>'
	+'               <span>jpg, jpeg, png, bmp, pdf (2MB × 1개)</span>'
	+'            </td>'
	+'         </tr>'
	+'      </table>'
	+'      <div>'
	+'         <a href="#"><input id="cancel" type="button" value="취소"/></a>'
	+'         <a href="#"><input id="confirm" type="button" value="확인"/></a>'
	+'      </div>'
	+'</div>';
}
function adminBbsFaqView(){
    return '<div id="page-wrapper">'
    +'			<div id="faq_table">'
    +'			<div>문의글 관리</div>'
    +'			<div id="faq_write_wrapper">'
    +'				<table>'
    +'				<colgroup>'
    +'					<col />'
    +'					<col />'
    +'					<col />'
    +'					<col />'
    +'					<col />'
    +'					<col />'
    +'				</colgroup>'
    +'					<tr>'
    +'						<th>순번</th>'
    +'						<th>제목</th>'
    +'						<th>작성자</th>'
    +'						<th>작성시간</th>'
    +'						<th>문답여부</th>'
    +'						<th>삭제</th>'
    +'					</tr>'
    +'					<tr>'
    +'					<td>4</td>'
    +'						<td><a id="question4" href="#">그것이 문제로다</a></td>'
    +'						<td>박준용</td>'
    +'						<td>2017-05-02</td>'
    +'						<td>X</td>'
    +'						<td><input type="button" value="x"/></td>'
    +'					</tr>'
    +'					<tr>'
    +'					<td>3</td>'
    +'						<td><a href="#">그것이 문제로다</a></td>'
    +'						<td>박준용</td>'
    +'						<td>2017-05-02</td>'
    +'						<td>X</td>'
    +'						<td><input type="button" value="x"/></td>'
    +'					</tr>'
    +'					<tr>'
    +'					<td>2</td>'
    +'						<td><a href="#">그것이 문제로다</a></td>'
    +'						<td>박준용</td>'
    +'						<td>2017-05-02</td>'
    +'						<td>X</td>'
    +'						<td><input type="button" value="x"/></td>'
    +'					</tr>'
    +'					<tr>'
    +'					<td>1</td>'
    +'						<td><a href="#">그것이 문제로다</a></td>'
    +'						<td>박준용</td>'
    +'						<td>2017-05-02</td>'
    +'						<td>X</td>'
    +'						<td><input type="button" value="x"/></td>'
    +'					</tr>'
    +'				</table>'
    +'				<div id="faq_pagination">'
    +'				   <table>'
    +'				      <tr>'
    +'				         <td>'
    +'				            <a href="#"><img src="'+$.image()+'/pagination/prev_all.gif" alt="" /></a>'
    +'				            <a href="#"><img src="'+$.image()+'/pagination/prev.gif" alt="" /></a>'
    +'				         </td>'
    +'				         <td>'
    +'				            <h4>'
    +'				            <a href="#">1</a>'
    +'				            <a href="#">2</a>'
    +'				            <a href="#">3</a>'
    +'				            <a href="#">4</a>'
    +'				            <a href="#">5</a>'
    +'				            <a href="#">6</a>'
    +'				            <a href="#">7</a>'
    +'				            <a href="#">8</a>'
    +'				            <a href="#">9</a>'
    +'				            <a href="#">10</a>'
    +'				            </h4>'
    +'				         </td>'
    +'				         <td>'
    +'				            <a href="#"><img src="'+$.image()+'/pagination/next.gif" alt="" /></a>'
    +'				            <a href="#"><img src="'+$.image()+'/pagination/next_all.gif" alt="" /></a>'
    +'				         </td>'
    +'				      </tr>'
    +'				   </table>'
    +'				  </div>'
    +'			</div>'
    +'			</div>'
    +'       </div>';
}
function adminBbsFaqAnswerView(){
    return '<div id="faq_answer">'
	+'	<div>'
	+'      <table>'
	+'         <tr>'
	+'            <td>'
	+'               <h3>영화관 관련 질문</h3>'
	+'               <ul>'
	+'                  <li>'
	+'                     <strong>카테고리 : </strong><span> 영화관</span>'
	+'                  </li>'
	+'                  <li>'
	+'                     <strong>등록일 : </strong><span> 2017-04-21</span>'
	+'                  </li>'
	+'                  <li>'
	+'                     <strong>조회수 : </strong><span> 27851</span>'
	+'                  </li>'
	+'               </ul>'
	+'            </td>'
	+'         </tr>'
	+'         <tr>'
	+'            <td colspan="2">'
	+'            <div id="faq_question_content">'
	+'            <span>국가는 재해를 예방하고 그 위험으로부터 국민을 보호하기 위하여 노력하여야 한다. 국가는 재해를 예방하고 그 위험으로부터 국민을 보호하기 위하여 노력하여야 한다. 국가는 재해를 예방하고 그 위험으로부터 국민을 보호하기 위하여 노력하여야 한다. 국가는 재해를 예방하고 그 위험으로부터 국민을 보호하기 위하여 노력하여야 한다. 국가는 재해를 예방하고 그 위험으로부터 국민을 보호하기 위하여 노력하여야 한다.</span>'
	+'            </div>'
	+'            </td>'
	+'         </tr>'
	+'         <tr>'
	+'            <td>'
	+'            <table id="faq_answer_content">'
	+'               <colgroup>'
	+'	               <col />'
	+'	               <col />'
	+'               </colgroup>'
	+'               <tr>'
	+'                  <td><textarea name="bbs_review_contents" id="bbs_review_contents" cols="30" rows="5"  placeholder="Write a comment..."></textarea></td>'
	+'                  <td><input id="bbs_review_contents_submit" type="submit" value="입력"/></td>'
	+'               </tr>'
	+'            </table>'
	+'            </td>'
	+'         </tr>'
	+'      </table>'
	+'      </div>'
	+'	</div>';
}
function reservationMainView(){
    return '<div id="reservation">'
	+'	   <div id="reservation_main_form">'
	+'		   <table>'
	+'		      <tr>'
	+'		         <td>'
	+'		         	<span>2017-04-27 <a href="#"><img src="'+$.image()+'/icon/calendar.png" alt="" width="30px" height="30px"/></a></span>'
	+'		         </td>'
	+'		      </tr>'
	+'		   </table>'
	+'	   <table id="reservation_multiplex">'
	+'	      <colgroup>'
	+'	      	<col />'
	+'	      	<col />'
	+'	      </colgroup>'
	+'	      <tr>'
	+'	         <td><span>영화관</span></td>'
	+'	         <td><span>영화</span></td>'
	+'	      </tr>'
	+'	      <tr>'
	+'	         <td>'
	+'		         <div id="reservation_tab_scroll">'
	+'			         <ul>'
	+'			            <li>'
	+'				            <span><a id="reservation_tab_cont" href="#">서울(<em>8</em>)</a></span>'
	+'				            <div id="reservation_area_list">'
	+'				            <ul>'
	+'				               <li><a href="#">가산디지털</a></li>'
	+'				               <li><a href="#">가양</a></li>'
	+'				               <li><a href="#">강동</a></li>'
	+'				               <li><a href="#">건대입구</a></li>'
	+'				               <li><a href="#">김포공항</a></li>'
	+'				               <li><a href="#">노원</a></li>'
	+'				               <li><a href="#">독산</a></li>'
	+'				               <li><a href="#">브로드웨이(신사)</a></li>'
	+'				               <li><a href="#">서울대입구</a></li>'
	+'				            </ul>'
	+'				            </div>'
	+'			            </li>'
	+'			         </ul>'
	+'			         <br />'
	+'		            <div id="reservation_area">'
	+'		            <ul>'
	+'		            	<li><a href="#">경기/인천</a></li>'
	+'		            	<li><a href="#">충청/대전</a></li>'
	+'		            	<li><a href="#">전라/광주</a></li>'
	+'		            	<li><a href="#">경북/대구</a></li>'
	+'		            	<li><a href="#">경남/부산/울산</a></li>'
	+'		            	<li><a href="#">강원</a></li>'
	+'		            	<li><a href="#">제주</a></li>'
	+'		            </ul>'
	+'		            </div>'
	+'		         </div>'
	+'	         </td>'
	+'	         <td>'
	+'		         <ul id="reservation_movielist">'
	+'		            <li><a href="#"><img src="'+$.image()+'/movie/grade_15.png" alt="" width="24px" height="24px"/> 특별시민</a></li>'
	+'		            <li><a href="#"><img src="'+$.image()+'/movie/grade_12.png" alt="" width="24px" height="24px"/> 임금님의 사건수첩</a></li>'
	+'		            <li><a href="#"><img src="'+$.image()+'/movie/grade_15.png" alt="" width="24px" height="24px"/> 분노의 질주: 더 익스트림</a></li>'
	+'		            <li><a href="#"><img src="'+$.image()+'/movie/grade_15.png" alt="" width="24px" height="24px"/> 보안관</a></li>'
	+'		            <li><a href="#"><img src="'+$.image()+'/movie/grade_all.png" alt="" width="24px" height="24px"/> 서서평, 천천히 평온하게</a></li>'
	+'		            <li><a href="#"><img src="'+$.image()+'/movie/grade_all.png" alt="" width="24px" height="24px"/> 스머프: 비밀의 숲</a></li>'
	+'		            <li><a href="#"><img src="'+$.image()+'/movie/grade_12.png" alt="" width="24px" height="24px"/> 가디언즈 오브 갤럭시 VOL.2</a></li>'
	+'		         </ul>'
	+'	         </td>'
	+'	      </tr>'
	+'	      <tr>'
	+'		      <td colspan="2">'
	+'		      <div id="reservation_confirm">'
	+'		         <div>'
	+'		         	<h3><span>상영시간</span></h3>'
	+'		         </div>'
	+'		      </div>'
	+'		      <div id="reservation_time">'
	+'		         <h4>가산디지털</h4>'
	+'			        <div id="movie_time_line">'
	+'						<div>'
	+'							<span id="movie_title"><strong>특별시민</strong></span><img src="'+$.image()+'/icon/movieLink.png" alt="" />'
	+'						</div>'
	+'						<ul id="movie_timeline_ul">'
	+'						<a href="javascript:abb1.jquery.reservation_seat()"><li><table>'
	+'							<tr>'
	+'							<td>1관</td>'
	+'							</tr>'
	+'							<tr>'
	+'							<td><strong>12:00</strong></td>'
	+'							</tr>'
	+'							<tr>'
	+'							<td> 50석 / 100석</td>'
	+'							</tr>'
	+'						</table>'
	+'						</li></a>'
	+'						<li>'
	+'						<table>'
	+'							<tr>'
	+'							<td>1관</td>'
	+'							</tr>'
	+'							<tr>'
	+'							<td><strong>12:00</strong></td>'
	+'							</tr>'
	+'							<tr>'
	+'							<td> 50석 / 100석</td>'
	+'							</tr>'
	+'						</table>'
	+'						</li>'
	+'						<li>'
	+'						<table>'
	+'							<tr>'
	+'							<td>1관</td>'
	+'							</tr>'
	+'							<tr>'
	+'							<td><strong>12:00</strong></td>'
	+'							</tr>'
	+'							<tr>'
	+'							<td> 50석 / 100석</td>'
	+'							</tr>'
	+'						</table>'
	+'						</li>'
	+'						<li>'
	+'						<table>'
	+'							<tr>'
	+'							<td>1관</td>'
	+'							</tr>'
	+'							<tr>'
	+'							<td><strong>12:00</strong></td>'
	+'							</tr>'
	+'							<tr>'
	+'							<td> 50석 / 100석</td>'
	+'							</tr>'
	+'						</table>'
	+'						</li>'
	+'						</ul>'
	+'					</div>'
	+'		      	</div>'
	+'		      </td>'
	+'	      </tr>'
	+'	   </table>'
	+'	   </div>'
	+'	</div>';
}
function reservationSeatView(){
    return '<div id="seat">'
	+'   	  <div id="reservation_seat_form">'
	+'      <div>'
	+'         <div>'
	+'            <span>좌석 선택</span>'
	+'         </div>'
	+'	      <div>'
	+'	         <span>Screen</span>'
	+'	      </div>'
	+'	      <div id="seat_area">'
	+'	      <div>'
	+'	         <table id="seat_area_table">'
	+'	            <colgroup>'
	+'	            	<col />'
	+'	            	<col />'
	+'	            </colgroup>'
	+'		         <tr>'
	+'		            <td>A</td>'
	+'		            <td>'
	+'		               <a href="#">1</a>'
	+'		               <a href="#">2</a>'
	+'		               <span></span>'
	+'		               <a href="#">3</a>'
	+'		               <a href="#">4</a>'
	+'		               <a class="reserved" href="#">5</a>'
	+'		               <a class="reserved" href="#">6</a>'
	+'		               <a href="#">7</a>'
	+'		               <a href="#">8</a>'
	+'		               <span></span>'
	+'		               <a href="#">9</a>'
	+'		               <a href="#">10</a>'
	+'		            </td>'
	+'		         </tr>'
	+'		         <tr>'
	+'		            <td>B</td>'
	+'		            <td>'
	+'		               <a class="reserved" href="#">1</a>'
	+'		               <a href="#">2</a>'
	+'		               <span></span>'
	+'		               <a href="#">3</a>'
	+'		               <a href="#">4</a>'
	+'		               <a href="#">5</a>'
	+'		               <a href="#">6</a>'
	+'		               <a href="#">7</a>'
	+'		               <a href="#">8</a>'
	+'		               <span></span>'
	+'		               <a href="#">9</a>'
	+'		               <a class="reserved" href="#">10</a>'
	+'		            </td>'
	+'		         </tr>'
	+'		         <tr>'
	+'		            <td>C</td>'
	+'		            <td>'
	+'		               <a href="#">1</a>'
	+'		               <a href="#">2</a>'
	+'		               <span></span>'
	+'		               <a href="#">3</a>'
	+'		               <a href="#">4</a>'
	+'		               <a href="#">5</a>'
	+'		               <a href="#">6</a>'
	+'		               <a href="#">7</a>'
	+'		               <a class="reserved" href="#">8</a>'
	+'		               <span></span>'
	+'		               <a class="reserved" href="#">9</a>'
	+'		               <a class="reserved" href="#">10</a>'
	+'		            </td>'
	+'		         </tr>'
	+'		         <tr>'
	+'		            <td>D</td>'
	+'		            <td>'
	+'		               <a class="reserved" href="#">1</a>'
	+'		               <a class="reserved" href="#">2</a>'
	+'		               <span></span>'
	+'		               <a class="reserved" href="#">3</a>'
	+'		               <a class="reserved" href="#">4</a>'
	+'		               <a class="reserved" href="#">5</a>'
	+'		               <a class="reserved" href="#">6</a>'
	+'		               <a href="#">7</a>'
	+'		               <a href="#">8</a>'
	+'		               <span></span>'
	+'		               <a href="#">9</a>'
	+'		               <a href="#">10</a>'
	+'		            </td>'
	+'		         </tr>'
	+'		         <tr>'
	+'		            <td>E</td>'
	+'		            <td>'
	+'		               <a href="#">1</a>'
	+'		               <a href="#">2</a>'
	+'		               <span></span>'
	+'		               <a href="#">3</a>'
	+'		               <a href="#">4</a>'
	+'		               <a href="#">5</a>'
	+'		               <a href="#">6</a>'
	+'		               <a class="reserved" href="#">7</a>'
	+'		               <a href="#">8</a>'
	+'		               <span></span>'
	+'		               <a href="#">9</a>'
	+'		               <a href="#">10</a>'
	+'		            </td>'
	+'		         </tr>'
	+'		         <tr>'
	+'		            <td>F</td>'
	+'		            <td>'
	+'		               <a href="#">1</a>'
	+'		               <a href="#">2</a>'
	+'		               <span></span>'
	+'		               <a href="#">3</a>'
	+'		               <a href="#">4</a>'
	+'		               <a href="#">5</a>'
	+'		               <a href="#">6</a>'
	+'		               <a href="#">7</a>'
	+'		               <a href="#">8</a>'
	+'		               <span></span>'
	+'		               <a href="#">9</a>'
	+'		               <a href="#">10</a>'
	+'		            </td>'
	+'		         </tr>'
	+'		         <tr>'
	+'		            <td>G</td>'
	+'		            <td>'
	+'		               <a href="#">1</a>'
	+'		               <a href="#">2</a>'
	+'		               <span></span>'
	+'		               <a href="#">3</a>'
	+'		               <a href="#">4</a>'
	+'		               <a href="#">5</a>'
	+'		               <a href="#">6</a>'
	+'		               <a href="#">7</a>'
	+'		               <a href="#">8</a>'
	+'		               <span></span>'
	+'		               <a href="#">9</a>'
	+'		               <a href="#">10</a>'
	+'		            </td>'
	+'		         </tr>'
	+'		         <tr>'
	+'		            <td>H</td>'
	+'		            <td>'
	+'		               <a href="#">1</a>'
	+'		               <a href="#">2</a>'
	+'		               <span></span>'
	+'		               <a href="#">3</a>'
	+'		               <a href="#">4</a>'
	+'		               <a href="#">5</a>'
	+'		               <a href="#">6</a>'
	+'		               <a href="#">7</a>'
	+'		               <a href="#">8</a>'
	+'		               <span></span>'
	+'		               <a href="#">9</a>'
	+'		               <a href="#">10</a>'
	+'		            </td>'
	+'		         </tr>'
	+'		         <tr>'
	+'		            <td>'
	+'		            </td>'
	+'		            <td>'
	+'		               <img src="'+$.image()+'/reservation/exit_bottom.png" alt="" />'
	+'		            </td>'
	+'		         </tr>'
	+'	         </table>'
	+'	      </div>'
	+'	      <div>'
	+'	         <img src="'+$.image()+'/reservation/seat_info.png" alt=""/>'
	+'	      </div>'
	+'	      </div>'
	+'      </div>'
	+'      </div>'
	+'   </div>'
	+'   <div id="ticketing">'
	+'	   <div>'
	+'	      <div>'
	+'	      <table>'
	+'	         <tr id="ticketing_tr1">'
	+'	            <td>'
	+'	               <div>영화</div>'
	+'	            </td>'
	+'	            <td>'
	+'	               <div>예매정보</div>'
	+'	            </td>'
	+'	            <td><div>총 결제 금액</div></td>'
	+'	         </tr>'
	+'	         <tr id="ticketing_tr2">'
	+'	            <td>'
	+'	            <table>'
	+'	               <tr>'
	+'	                  <td><img src="'+$.image()+'/movie/movie_poster_6.png" alt="" width="127px" height="170px"/></td>'
	+'	                  <td>'
	+'		                  <div id="ticketing_movie_title">아빠는 딸</div>'
	+'		                  <div id="ticketing_movie_type">2D</div>'
	+'		                  <div id="">15세이상관람가</div>'
	+'	                  </td>'
	+'	               </tr>'
	+'	            </table>'
	+'	            </td>'
	+'	            <td>'
	+'		            <table>'
	+'	                  <tr>'
	+'	                     <td>상영일</td>'
	+'	                     <td>2017-04-27(목)</td>'
	+'	                  </tr>'
	+'	                  <tr>'
	+'	                     <td>상영시간</td>'
	+'	                     <td>19:00~21:00</td>'
	+'	                  </tr>'
	+'	                  <tr>'
	+'	                     <td>상영관</td>'
	+'	                     <td>가산디지털 1관</td>'
	+'	                  </tr>'
	+'	                  <tr>'
	+'	                     <td>좌석</td>'
	+'	                     <td>A1</td>'
	+'	                  </tr>'
	+'	                  <tr>'
	+'	                     <td id="ticketing_cost" colspan="2">9,000원</td>'
	+'	                  </tr>'
	+'	               </table>'
	+'	            </td>'
	+'	            <td id="ticketing_paying">'
	+'		            <div id="ticketing_cost_total">9,000원</div>'
	+'		            <a href="${context}/customer/mypage"><input type="button" value="결제하기"/></a>'
	+'	            </td>'
	+'	         </tr>'
	+'	      </table>'
	+'	      </div>'
	+'	   </div>'
	+'   </div>';
}
function adminLoginView(){
	return '<div id="signupSuccess">'
	+'		<div id="signup_success">'
	+'			<div>'
	+'				<table>'
	+'		         <tr>'
	+'		         	<td>'
	+'			         	<h3><strong>관리자</strong><span>님 환영합니다!</span></h3>'
	+'		         	</td>'
	+'		         </tr>'
	+'		         <tr>'
	+'			         <td>'
	+'			         <ul>'
	+'						 <li>'
	+'							<a href="${context}/admin/index"><input type="button" value="관리자 페이지 GO"/></a>'
	+'						 </li>'
	+'					 </ul>'
	+'					 </td>'
	+'		         </tr>'
	+'		      	</table>'
	+'			</div>'
	+'		</div>'
	+'	</div>';
}
function customerSignUpView(){
	return '<div id="signUp">'
    	+'	    <div>'
    	+'	      <h2>회원가입</h2>'
    	+'	      <div id="signup_tables">'
    	+'	         <table>'
    	+'	            <tr>'
    	+'	               <td><input id="id" name="id" type="text" placeholder="아이디"></td>'
    	+'	            </tr>'
    	+'	            <tr>'
    	+'	               <td id="result_id_msg"></td>'
    	+'	            </tr>'
    	+'	            <tr>'
    	+'	               <td><input id="pw" name="pw" type="password" placeholder="비밀번호"></td>'
    	+'	            </tr>'
    	+'	            <tr>'
    	+'	               <td id="result_pw_msg"></td>'
    	+'	            </tr>'
    	+'	            <tr>'
    	+'	               <td><input id="check_pw" type="password" placeholder="비밀번호 확인"></td>'
    	+'	            </tr>'
    	+'	            <tr>'
    	+'	               <td id="check_pw_msg"></td>'
    	+'	            </tr>'
    	+'	         </table>'
    	+'	         <table>'
    	+'	            <tr>'
    	+'	               <td colspan="3"><input id="name" name="name" type="text" placeholder="이름"></td>'
    	+'	            </tr>'
    	+'	            <tr>'
    	+'	               <td><input id="year" name="year" type="text" placeholder="생년"></td>'
    	+'	            <td>'
    	+'	               <select id="month" name="month">'
    	+'	                  <option value="" selected>월</option>'
    	+'	                  <option value="1">1</option>'
    	+'	                  <option value="2">2</option>'
    	+'	                  <option value="3">3</option>'
    	+'	                  <option value="4">4</option>'
    	+'	                  <option value="5">5</option>'
    	+'	                  <option value="6">6</option>'
    	+'	                  <option value="7">7</option>'
    	+'	                  <option value="8">8</option>'
    	+'	                  <option value="9">9</option>'
    	+'	                  <option value="10">10</option>'
    	+'	                  <option value="11">11</option>'
    	+'	                  <option value="12">12</option>'
    	+'	               </select>'
    	+'	            </td>'
    	+'	            <td><input id="date" name="date" type="text" placeholder="일"></td>'
    	+'	         </tr>'
    	+'	         <tr>'
    	+'	            <td><input id="phone1" name="phone1" type="text" placeholder="010"></td>'
    	+'	            <td><input id="phone2" name="phone2" type="text"></td>'
    	+'	            <td><input id="phone3" name="phone3" type="text"></td>'
    	+'	         </tr>'
    	+'	      </table>'
    	+'	      <table>'
    	+'	         <tr>'
    	+'	            <td><div><input type="radio" id="male" name="gender" value="M" checked="checked"/><label id="manLb" for="man">남자</label></div></td>'
    	+'	            <td><div><input type="radio" id="female" name="gender" value="F"/><label id="womanLb" for="woman">여자</label></div></td>'
    	+'	         </tr>'
    	+'	      </table>'
    	+'	      <table>'
    	+'	      	<tr>'
    	+'	            <td><input type="text" placeholder="주소" ></td>'
    	+'	            <td>'
    	+'	               <input id="find_postcode" type="button" value="우편번호 검색" type="submit">'
    	+'	            </td>'
    	+'	         </tr>'
    	+'	      	<tr>'
    	+'              <td colspan="2"><input type="text" placeholder="주소"></td>'
    	+'	        </tr>'
    	+'	      	<tr>'
    	+'              <td colspan="2"><input type="text" placeholder="상세주소"></td>'
    	+'	        </tr>'
    	+'	      </table>'
    	+'	      <table>'
    	+'	         <tr>'
    	+'	            <td colspan="2"><input id="email" name="email" type="text" placeholder="이메일" ></td>'
    	+'	            <td>'
    	+'	               <input id="send_code" type="button" value="인증번호 발송" type="submit">'
    	+'	            </td>'
    	+'	         </tr>'
    	+'	         <tr>'
    	+'	            <td colspan="3"><input type="text" placeholder="인증번호 입력"></td>'
    	+'	         </tr>'
    	+'	      </table>'
    	+'	      	<a href="javascript:abb1.jquery.customer_signupsuccess()"><input id="signup_finish" type="button" value="가입하기"/></a>'
    	+'	      </div>'
    	+'	   </div> '  
    	+'	</div>';
}
function customerUpdateInfoView(){
	 return '<div id="signUp">'
	    	+'	    <div>'
	    	+'	      <h2><strong>회원정보변경</strong></h2>'
	    	+'			<div id="updateInfo">'
	    	+'				<table>'
	    	+'					<tr>'
	    	+'						<td><strong>아이디</strong></td>'
	    	+'						<td id="id">yheisun</td>'
	    	+'					</tr>'
	    	+'					<tr>'
	    	+'						<td><strong>비밀번호</strong></td>'
	    	+'						<td><input id="pw" type="password" placeholder="비밀번호"><span id="result_pw_msg"></span><input id="check_pw" type="password" placeholder="비밀번호 확인"><h6 id="check_pw_msg"></h6></td>'
	    	+'					</tr>'
	    	+'					<tr>'
	    	+'						<td><strong>성명</strong></td>'
	    	+'						<td id="name">염혜선</td>'
	    	+'					</tr>'
	    	+'					<tr>'
	    	+'						<td><strong>생년</strong></td>'
	    	+'						<td id="birth">1992년 10월 15일</td>'
	    	+'					</tr>'
	    	+'					<tr>'
	    	+'						<td><strong>성별</strong></td>'
	    	+'						<td id="gender">여자</td>'
	    	+'					</tr>'
	    	+'					<tr>'
	    	+'						<td><strong>이메일</strong></td>'
	    	+'						<td id="email">yheisun@gmail.com</td>'
	    	+'					</tr>'
	    	+'					<tr>'
	    	+'				</table>'
	    	+'				<table>'
	    	+'					<tr>'
	    	+'						<td><input id="phone1" type="text" placeholder="010"></td>'
	    	+'						<td><input id="phone2" type="text"></td>'
	    	+'						<td><input id="phone3" type="text"></td>'
	    	+'					</tr>'
	    	+'				</table>'
	    	+'				<table>'
	    	+'					<tr>'
	    	+'						<td><input type="text" placeholder="주소"></td>'
	    	+'						<td><input id="find_postcode" type="button" value="우편번호 검색"></td>'
	    	+'					</tr>'
	    	+'					<tr>'
	    	+'						<td colspan="2"><input type="text" placeholder="주소"></td>'
	    	+'					</tr>'
	    	+'					<tr>'
	    	+'						<td colspan="2"><input type="text" placeholder="상세주소"></td>'
	    	+'					</tr>'
	    	+'				</table>'
	    	+'				<ul>'
	    	+'					<li>'
	    	+'						<a href="javascript:abb1.jquery.customer_mypageInfo()"><input id="cancel" type="button" value="취소"/></a>'
	    	+'					</li>'
	    	+'					<li>'
	    	+'						<a href="#"><input id="confirm" type="button" value="확인"/></a>'
	    	+'					</li>'
	    	+'				</ul>'
	    	+'			</div>'
	    	+'		</div>'
	    	+'	</div>';
}
function customerMypageView(){
	return '<div id="mypage" class="abb1_find_id_container">'
    	+'		<div> '
    	+'			<h2><strong>마이시네마</strong></h2><h4><strong>내 포인트</strong>: <span id="point"></span>점</h4>'
    	+'		</div>'
    	+'		<div id="mypageGnb">'
    	+'			<ul>'
    	+'				<li>'
    	+'					<a href="#">예매/구매내역</a>'
    	+'				</li>'
    	+'				<li>'
    	+'					<a href="javascript:abb1.jquery.customer_mypageInfo()">나의 정보관리</a>'
    	+'				</li>'
    	+'			</ul> '
    	+'		</div>'
    	+'		<div id="mypage_reservation_content">'
    	+'			<ul>'
    	+'				<li>'
    	+'					<a href="#"><strong>예매/구매내역</strong></a>'
    	+'				</li>'
    	+'				<li>'
    	+'					<a href="javascript:abb1.jquery.customer_mypageCancel()">취소내역</a>'
    	+'				</li>'
    	+'			</ul>'
    	+'			<div id="mypage_reservation">'
    	+'			</div>'
    	+'		</div>'
    	+'	</div>';
    
}

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
function customer_mypage_view(){
	var view='<div id="mypage">'
    	+'		<div> '
    	+'			<h2><strong>마이시네마</strong></h2><h4><strong>내 포인트</strong>: <span id="point"></span>점</h4>'
    	+'		</div>'
    	+'		<div id="mypageGnb">'
    	+'			<ul>'
    	+'				<li>'
    	+'					<a href="#">예매/구매내역</a>'
    	+'				</li>'
    	+'				<li>'
    	+'					<a href="javascript:abb1.jquery.customer_mypageInfo()">나의 정보관리</a>'
    	+'				</li>'
    	+'			</ul> '
    	+'		</div>'
    	+'		<div id="mypage_reservation_content">'
    	+'			<ul>'
    	+'				<li>'
    	+'					<a href="#"><strong>예매/구매내역</strong></a>'
    	+'				</li>'
    	+'				<li>'
    	+'					<a href="javascript:abb1.jquery.customer_mypageCancel()">취소내역</a>'
    	+'				</li>'
    	+'			</ul>'
    	+'			<div id="mypage_reservation">'
    	+'			</div>'
    	+'		</div>'
    	+'	</div>';
    $('#container').html(view);
}

function customer_mypage_css(length){
	var mypage = $('#mypage');
	mypage.addClass('abb1_find_id_container');
	$('#mypageGnb').addClass('abb1_padding_top_20 abb1_width_left');
	mypage.find('table').css('margin','15px');
	mypage.find('div:first-child').addClass('abb1_width_left');
	mypage.find('div:first-child').find('h2').addClass('abb1_color_bold_brown');
	mypage.find('div:nth-child(2)').find('ul').addClass('abb1_page_ul_inline');
	mypage.find('div:nth-child(2)').find('li').addClass('abb1_page_li_inline');
	mypage.find('div:nth-child(2)').find('li:nth-child(1)').find('a').addClass('abb1_mypage_select_btn');
	mypage.find('div:nth-child(2)').find('li:nth-child(2)').find('a').addClass('abb1_mypage_not_select_btn');
	var mypage_reservation_content = $('#mypage_reservation_content');
	mypage_reservation_content.addClass('abb1_mypage_reservation_content');
	mypage_reservation_content.find('ul').addClass('abb1_page_ul_inline abb1_mypage_margin');
	mypage_reservation_content.find('li').addClass('abb1_page_li_inline');
	mypage_reservation_content.find('li').find('a').addClass('abb1_detail_gnb_li');
	var mypage_reservation = $('#mypage_reservation');
	mypage_reservation.addClass('abb1_page_reservation');
	mypage_reservation.find('tr:first-child').addClass('abb1_margin_left_20');
	mypage_reservation.find('tr:nth-child(2)').find('td:nth-child(3)').addClass('abb1_text_right');
	mypage.find('table>tr:nth-child(3)>td:nth-child(3)').css('text-align','right');
	$('#default_msg').css('padding-left','20px');
	mypage.find('div:first-child>h4').addClass('abb1_width_right');
	for(var i=0;i<length;i++){
		$('#movie_img'+i+'').css('padding-right','35px');
		$('#reservation_pic'+i+'').addClass('abb1_margin_left_20');
		$('#reservation_no'+i+'').addClass('abb1_margin_right_20');
		$('#detail_icon'+i+'').css('text-align','right');
		$('#price_title'+i+'').css('padding-right','25px');
	}
}

function css(){
	var mypage = $('#mypage');
	mypage.addClass('abb1_find_id_container');
	$('#mypageGnb').addClass('abb1_padding_top_20 abb1_width_left');
	mypage.find('table').css('margin','15px');
	mypage.find('div:first-child').addClass('abb1_width_left');
	mypage.find('div:first-child').find('h2').addClass('abb1_color_bold_brown');
	mypage.find('div:nth-child(2)').find('ul').addClass('abb1_page_ul_inline');
	mypage.find('div:nth-child(2)').find('li').addClass('abb1_page_li_inline');
	mypage.find('div:nth-child(2)').find('li:nth-child(1)').find('a').addClass('abb1_mypage_select_btn');
	mypage.find('div:nth-child(2)').find('li:nth-child(2)').find('a').addClass('abb1_mypage_not_select_btn');
	var mypage_reservation_content = $('#mypage_reservation_content');
	mypage_reservation_content.addClass('abb1_mypage_reservation_content');
	mypage_reservation_content.find('ul').addClass('abb1_page_ul_inline abb1_mypage_margin');
	mypage_reservation_content.find('li').addClass('abb1_page_li_inline');
	mypage_reservation_content.find('li').find('a').addClass('abb1_detail_gnb_li');
	var mypage_reservation = $('#mypage_reservation');
	mypage_reservation.addClass('abb1_page_reservation');
	mypage_reservation.find('tr:first-child').addClass('abb1_margin_left_20');
	mypage_reservation.find('tr:nth-child(2)').find('td:nth-child(3)').addClass('abb1_text_right');
	mypage.find('table>tr:nth-child(3)>td:nth-child(3)').css('text-align','right');
	$('#default_msg').css('padding-left','20px');
	mypage.find('div:first-child>h4').addClass('abb1_width_right');
}

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
function customerMypageReservationTable(i){
	return '<div id="mypage_table'+i+'">	<table>'
	+'					<tr>'
	+'						<td id="movie_img'+i+'" rowspan="5"><span id="reservation_pic'+i+'"><img id="movie_poster'+i+'" src="" width="115px" height="150px" alt="" /></span></td>'
	+'						<td><span id="reservation_no'+i+'">예매번호</span></td>'
	+'						<td id="reservation_number'+i+'">123456789</td>'
	+'					</tr>'
	+'					<tr>'
	+'						<td>예매일</td>'
	+'						<td colspan="2" id="reservation_date'+i+'">2017-04-21</td>'
	+'					</tr>'
	+'					<tr>'
	+'						<td>사용상태</td>'
	+'						<td id="canceled'+i+'">취소가능</td>'
	+'						<td id="detail_icon'+i+'"><a id="detail_'+i+'" class="abb1_detail_icon" href="#">상세<img src="'+$.image()+'/icon/downarrow.png" width="3%" height="3%" alt="" /></a></td>'
	+'					</tr>'
	+'					<tr>'
	+'						<td>예매내역</td>'
	+'						<td colspan="2" id="movie_name'+i+'">아빠는 딸</td>'
	+'					</tr>'
	+'					<tr>'
	+'						<td id="price_title'+i+'">총 결제 금액</td>'
	+'						<td colspan="2" id="reservation_price'+i+'">22,000원</td>'
	+'					</tr>'
	+'				</table></div>'
}
function customerFindIdView(){
	return '<div id="customer_find_id">'
	+'		<div> '
	+'			<h2><strong>회원 ID 찾기</strong></h2>'
	+'		</div>'
	+'		<div id="customer_find_id_div">'
	+'			<div>'
	+'				<table id="customer_find_id_table">'
	+'			         <tr>'
	+'			         	<td><strong>이름</strong></td>'
	+'			            <td colspan="2"><input type="text"></td>'
	+'			         </tr>'
	+'			         <tr>'
	+'			         	<td><strong>이메일</strong></td>'
	+'			            <td colspan="2"><input type="text" ></td>'
	+'			         </tr>'
	+'			         <tr>'
	+'			         <td><span>인증번호를 받을</span></td>'
	+'		         <td><span>이메일를 입력하세요.</span></td>'
	+'			         <td><input id="customer_send_email" type="button" value="전송"></td>'
	+'			         </tr>'
	+'			         <tr>'
	+'			         	<td><strong>인증번호</strong></td>'
	+'			            <td colspan="2"><input type="text"></td>'
	+'			         </tr>'
	+'			         <tr>'
	+'			         <td colspan="3" id="customer_find_id_btns">'
	+'			         <ul>'
	+'						<li>'
	+'							<a href="javascript:abb1.jquery.customer_login()"><input type="button" value="취소"/></a>'
	+'						</li>'
	+'						<li>'
	+'							<a href="javascript:abb1.jquery.customer_findidsuccess()"><input type="button" value="확인"  /></a>'
	+'						</li>'
	+'					</ul></td>'
	+'		         	</tr>'
	+'		      	</table>'
	+'			</div>'
	+'		</div>'
	+'	</div>';
}
function customerFindIdSuccessView(){
	return '<div id="customer_find_id">'
	+'		<div> '
	+'			<h2><strong>회원 ID 찾기</strong></h2>'
	+'		</div>'
	+'		<div id="customer_find_id_result">'
	+'			<div>'
	+'				<table id="customer_find_id_table">'
	+'		         <tr>'
	+'			         <td>'
	+'			         	<h4>회원님의 아이디는 <strong>yheisun</strong>입니다.</h4>'
	+'			         </td>'
	+'		         </tr>'
	+'		         <tr>'
	+'		         	<td>'
	+'			        <ul>'
	+'						<li>'
	+'							<a href="'+ctx+'/customer/login"><input type="button" value="확인"  /></a>'
	+'						</li>'
	+'					</ul>'
	+'					</td>'
	+'		         </tr>'
	+'		      </table>'
	+'			</div>'
	+'		</div>'
	+'	</div>';
}
function customerFindPwView(){
	return '<div id="customer_find_pw">'
	+'		<div> '
	+'			<h2><strong>회원 비밀번호 찾기</strong></h2>'
	+'		</div>'
	+'		<div id="customer_find_pw_div">'
	+'			<div>'
	+'				<table id="customer_find_pw_table">'
	+'		         <tr>'
	+'		         	<td><strong>아이디</strong></td>'
	+'		            <td colspan="2"><input type="text"></td>'
	+'		         </tr>'
	+'		         <tr>'
	+'		         	<td><strong>이메일</strong></td>'
	+'		            <td colspan="2"><input type="text"></td>'
	+'		         </tr>'
	+'		         <tr>'
	+'			         <td><span>인증번호를 받을</span></td>'
	+'			         <td><span>이메일를 입력하세요.</span></td>'
	+'			         <td><input id="customer_send_email" type="button" value="전송"></td>'
	+'		         </tr>'
	+'		         <tr>'
	+'		         	<td><strong>인증번호</strong></td>'
	+'		            <td colspan="2"><input type="text"></td>'
	+'		         </tr>'
	+'		         <tr>'
	+'		         <td colspan="3" id="customer_find_pw_btns">'
	+'			         <ul>'
	+'						<li>'
	+'							<a href="javascript:abb1.jquery.customer_login()"><input type="button" value="취소"  /></a>'
	+'						</li>'
	+'						<li>'
	+'							<a href="javascript:abb1.jquery.customer_findpwsuccess()"><input type="button" value="확인"  /></a>'
	+'						</li>'
	+'					</ul>'
	+'				</td>'
	+'		         </tr>'
	+'		      </table>'
	+'			</div>'
	+'		</div>'
	+'	</div>';
}
function customerFindPwSuccessView(){
	return '<div id="customer_find_pw">'
	+'		<div> '
	+'			<h2><strong>회원 비밀번호 찾기</strong></h2>'
	+'		</div>'
	+'		<div id="customer_find_pw_result">'
	+'			<div>'
	+'				<table id="customer_find_pw_table">'
	+'		         <tr>'
	+'		         	<td><strong>비밀번호</strong></td>'
	+'		            <td colspan="2"><input type="text"></td>'
	+'		         </tr>'
	+'		         <tr>'
	+'		         	<td><strong>비밀번호 확인</strong></td>'
	+'		            <td colspan="2"><input type="text"></td>'
	+'		         </tr>'
	+'		         <tr>'
	+'		         	<td colspan="3" id="customer_find_pw_btns">'
	+'			        <ul>'
	+'					<li>'
	+'						<a href="'+ctx+'/customer/login"><input type="button" value="취소"  /></a>'
	+'					</li>'
	+'					<li>'
	+'						<a href="'+ctx+'/customer/login"><input type="button" value="확인"  /></a>'
	+'					</li>'
	+'					</ul>'
	+'					</td>'
	+'		         </tr>'
	+'		      </table>'
	+'			</div>'
	+'		</div>'
	+'	</div>';
}
function customerMypageCancelView(){
	return '<div id="mypage">'
	+'		<div> '
	+'			<h2><strong>마이시네마</strong></h2>'
	+'		</div>'
	+'		<div id="mypageGnb">'
	+'			<ul>'
	+'				<li>'
	+'					<a href="#">예매/구매내역</a>'
	+'				</li>'
	+'				<li>'
	+'					<a href="javascript:abb1.jquery.customer_mypageInfo()">나의 정보관리</a>'
	+'				</li>'
	+'			</ul> '
	+'		</div>'
	+'		<div id="mypage_reservation_content">'
	+'			<ul>'
	+'				<li>'
	+'					<a href="javascript:abb1.jquery.customer_mypage()"><strong>예매/구매내역</strong></a>'
	+'				</li>'
	+'				<li>'
	+'					<a href="#">취소내역</a>'
	+'				</li>'
	+'			</ul>'
	+'			<div id="mypage_reservation">'
	+'				<table>'
	+'					<tr>'
	+'						<td rowspan="4"><span id="reservation_pic"><img src="'+ctx+'/resources/img/movie/movie_poster_6.png" width="60%" height="60%" alt="" /></span></td>'
	+'						<td><span id="reservation_no">예매번호(예매일)</span></td>'
	+'						<td colspan="2"><span>123456789</span>(2017-04-21)</td>'
	+'					</tr>'
	+'					<tr>'
	+'						<td>사용상태</td>'
	+'						<td>취소완료(2017-04-22)</td>'
	+'					</tr>'
	+'					<tr>'
	+'						<td>예매내역</td>'
	+'						<td colspan="2">아빠는 딸</td>'
	+'					<tr>'
	+'						<td>총 결제 금액</td>'
	+'						<td colspan="2">22,000원</td>'
	+'					</tr>'
	+'				</table>'
	+'			</div>'
	+'		</div>'
	+'	</div>';
}
function customerMypageInfoView(){
	return '<div id="mypage">'
	+'		<div> '
	+'			<h2><strong>마이시네마</strong></h2>'
	+'		</div>'
	+'		<div id="mypageGnb">'
	+'			<ul>'
	+'				<li>'
	+'					<a href="javascript:abb1.jquery.customer_mypage()">예매/구매내역</a>'
	+'				</li>'
	+'				<li>'
	+'					<a href="#">나의 정보관리</a>'
	+'				</li>'
	+'			</ul> '
	+'		</div>'
	+'		<div id="mypage_reservation_content">'
	+'			<div>'
	+'				<ul>'
	+'					<li>'
	+'						<a href="javascript:abb1.jquery.customer_updateInfoChPw()"><input type="button" value="회원정보변경" /></a>'
	+'					</li>'
	+'					<li>'
	+'						<a href="javascript:abb1.jquery.customer_withdrawal()"><input type="button" value="회원탈퇴" /></a>'
	+'					</li>'
	+'				</ul>'
	+'			</div>'
	+'		</div>'
	+'	</div>';
}
function customerMypageReservationView(){
	return '<div id="mypage">'
	+'		<div> '
	+'			<h2><strong>마이시네마</strong></h2>'
	+'		</div>'
	+'		<div id="mypageGnb">'
	+'			<ul>'
	+'				<li>'
	+'					<a href="#">예매/구매내역</a>'
	+'				</li>'
	+'				<li>'
	+'					<a href="'+ctx+'/customer/mypageInfo">나의 정보관리</a>'
	+'				</li>'
	+'			</ul> '
	+'		</div>'
	+'		<div id="mypage_reservation_content">'
	+'			<ul>'
	+'				<li>'
	+'					<a href="#"><strong>예매/구매내역</strong></a>'
	+'				</li>'
	+'				<li>'
	+'					<a href="javascript:abb1.jquery.customer_mypageCancel()">취소내역</a>'
	+'				</li>'
	+'			</ul>'
	+'			<div id="mypage_reservation">'
	+'				<table>'
	+'					<tr>'
	+'						<td rowspan="4"><span id="reservation_pic"><img src="'+ctx+'/resources/img/movie/movie_poster_6.png" width="60%" height="60%" alt="" /></span></td>'
	+'						<td><span id="reservation_no">예매번호(예매일)</span></td>'
	+'						<td colspan="2"><span>123456789</span>(2017-04-21)</td>'
	+'					</tr>'
	+'					<tr>'
	+'						<td>사용상태</td>'
	+'						<td>취소가능</td>'
	+'						<td><a href="javascript:abb1.jquery.customer_mypage()">닫기<img src="'+ctx+'/resources/img/icon/uparrow.png" width="3%" height="3%" alt="" /></a></td>'
	+'					</tr>'
	+'					<tr>'
	+'						<td>예매내역</td>'
	+'						<td colspan="2">아빠는 딸</td>'
	+'					</tr>'
	+'					<tr>'
	+'						<td>총 결제 금액</td>'
	+'						<td colspan="2">22,000원</td>'
	+'					</tr>'
	+'				</table>'
	//
	+'				<div id="detail_reservation">'
	+'					<div>'
	+'						<h4>상세내용</h4>'
	+'					</div>'
	+'					<div>'
    	+'					<table>'
    	+'						<tr>'
    	+'							<td rowspan="4"><span id="detail_reservation_pic"><img src="'+ctx+'/resources/img/movie/movie_poster_6.png" width="60%" height="60%" alt="" /></span></td>'
    	+'							<td colspan="2"><h4><strong>아빠는 딸</strong></h4></td>'
    	+'						</tr>'
    	+'						<tr>'
    	+'							<td>상영일</td>'
    	+'							<td>2017-04-23 | 상영시간 13:50 ~ 15:55 | 상영관 가산디지털, 1관</td>'
    	+'						</tr>'
    	+'						<tr>'
    	+'							<td>관람인원</td>'
    	+'							<td>성인2 | 좌석 E10,E11</td>'
    	+'						</tr>'
    	+'						<tr>'
    	+'							<td><span>주문금액</span></td>'
    	+'							<td>22,000원</td>'
    	+'						</tr>'
    	+'					</table>'
	+'					</div>'
	+'					<div>'
	+'						<input id="reservation_cancel" type="button" value="결제취소"  />'
	+'					</div>'
	+'				</div>'
	//
	+'			</div>'
	+'		</div>'
	+'	</div>';
}
function customerSignUpSuccessView(){
	return '<div id="signupSuccess">'
	+'		<div> '
	+'			<h2><strong>가입완료</strong></h2>'
	+'		</div>'
	+'		<div id="signup_success">'
	+'			<div>'
	+'				<table>'
	+'		         <tr>'
	+'		         	<td>'
	+'			         	<h3><strong>염혜선</strong><span>님 환영합니다!</span></h3>'
	+'		         	</td>'
	+'		         </tr>'
	+'		         <tr>'
	+'			         <td>'
	+'			         <ul>'
	+'						 <li>'
	+'							<a href="'+ctx+'"><input type="button" value="확인"/></a>'
	+'						 </li>'
	+'					 </ul>'
	+'					 </td>'
	+'		         </tr>'
	+'		      	</table>'
	+'			</div>'
	+'		</div>'
	+'	</div>';
}
function customerUpdateInfoChPwView(){
	return '<div id="updateInfoChPw">'
	+'	<div> '
	+'			<h2><strong>회원정보변경</strong></h2>'
	+'		</div>'
	+'		<div id="signup_success">'
	+'			<div>'
	+'				<table>'
	+'		         <tr>'
	+'		         	<td><strong>아이디</strong></td>'
	+'		            <td id="id">yheisun</td>'
	+'		         </tr>'
	+'		         <tr>'
	+'		         	<td><strong>비밀번호</strong></td>'
	+'		            <td><input id="pw" type="password"></td>'
	+'		         </tr>'
	+'		         <tr>'
	+'		         	<td colspan="2">'
	+'		         	<ul>'
	+'						<li>'
	+'							<a href="javascript:abb1.jquery.customer_mypageInfo()"><input type="button" value="취소"  /></a>'
	+'						</li>'
	+'						<li class="abb1_page_li_inline">'
	+'							<a href="#"><input id="go_update_info" type="button" value="확인"  /></a>'
	+'						</li>'
	+'					</ul>'
	+'					</td>'
	+'		         </tr>'
	+'		      </table>'
	+'			</div>'
	+'		</div>'
	+'	</div>';
}
function customerWithdrawalView(){
	return '<div id="mypageWithdrawal">'
	+'		<div> '
	+'			<h2><strong>회원탈퇴</strong></h2>'
	+'		</div>'
	+'		<div id="withdrawal">'
	+'			<div>'
	+'				<table>'
	+'		         <tr>'
	+'		         	 <td><h3 id="comment">탈퇴를 하시겠습니까?</h3></td>'
	+'		         </tr>'
	+'		         <tr>'
	+'			         <td>'
	+'				        <ul id="ul_btn">'
	+'						<li>'
	+'							<a href="javascript:abb1.jquery.customer_mypageInfo()"><input type="button" value="취소"  /></a>'
	+'						</li>'
	+'						<li>'
	+'							<a href="#"><input id="withdrawal_btn" type="button" value="확인"  /></a>'
	+'						</li>'
	+'						</ul>'
	+'					</td>'
	+'		         </tr>'
	+'		      </table>'
	+'			</div>'
	+'		</div>'
	+'	</div>';
}