CREATE TABLE Board(
seq INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
type VARCHAR(4) NOT NULL,
title VARCHAR(50) NOT NULL,
contents VARCHAR(500),
file VARCHAR(200),
date VARCHAR(10) NOT NULL,
hits VARCHAR(4) NOT NULL,
customer_id VARCHAR(15),
theater_id INT,
comment_seq INT
);

CREATE TABLE Theater(
seq INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(20) NOT NULL,
address VARCHAR(40) NOT NULL,
total_multiplex VARCHAR(2) NOT NULL,
total_seat VARCHAR(3) NOT NULL,
axis VARCHAR(40) NOT NULL,
multiplex_id INT
);

CREATE TABLE Multiplex(
seq INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(4) NOT NULL,
total_seat VARCHAR(3) NOT NULL,
reser_seat_no VARCHAR(3) NOT NULL,
start_time VARCHAR(5) NOT NULL,
end_time VARCHAR(5) NOT NULL,
price VARCHAR(5) NOT NULL,
seat_id VARCHAR(11),
movie_id INT
);

CREATE TABLE Comment(
seq INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
date VARCHAR(10) NOT NULL,
contents VARCHAR(300) NOT NULL,
customer_id VARCHAR(15)
);

CREATE TABLE Customer(
id VARCHAR(15) PRIMARY KEY,
pw VARCHAR(15) NOT NULL,
name VARCHAR(15) NOT NULL,
gender VARCHAR(1) NOT NULL,
birth VARCHAR(6) NOT NULL,
address VARCHAR(40) NOT NULL,
phone VARCHAR(11) NOT NULL,
email VARCHAR(30) NOT NULL,
point VARCHAR(5) NOT NULL
);

CREATE TABLE Reservation(
id VARCHAR(30) PRIMARY KEY,
date VARCHAR(10) NOT NULL,
headcount VARCHAR(2) NOT NULL,
is_canceled VARCHAR(1) NOT NULL,
customer_id VARCHAR(15),
movie_id INT,
multiplex_id INT,
theater_id INT,
seat_id VARCHAR(11)
);

CREATE TABLE Seat(
id VARCHAR(11) PRIMARY KEY,
is_reserved VARCHAR(1) NOT NULL
);

CREATE TABLE Notice(
seq INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
file VARCHAR(200),
title VARCHAR(50) NOT NULL,
contents VARCHAR(500) NOT NULL,
date VARCHAR(10) NOT NULL,
hits VARCHAR(4) NOT NULL
);

CREATE TABLE Review(
seq INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
type VARCHAR(8) NOT NULL,
gpa VARCHAR(2) NOT NULL,
contents VARCHAR(300) NOT NULL,
date VARCHAR(10) NOT NULL,
customer_id VARCHAR(15)
);

CREATE TABLE Movie(
seq INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(30) NOT NULL,
rate VARCHAR(6) NOT NULL,
gpa VARCHAR(3) NOT NULL,
grade VARCHAR(2) NOT NULL,
release_date VARCHAR(10) NOT NULL,
info VARCHAR(40) NOT NULL,
synopsys VARCHAR(500) NOT NULL,
casting VARCHAR(200) NOT NULL,
male_p VARCHAR(4) NOT NULL,
female_p VARCHAR(4) NOT NULL,
trailer_url VARCHAR(200) NOT NULL,
review_seq INT,
files_id INT
);

CREATE TABLE Files(
seq INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
pic_main VARCHAR(200) NOT NULL,
pic_director VARCHAR(200),
pic_actor1 VARCHAR(200),
pic_actor2 VARCHAR(200),
pic_actor3 VARCHAR(200),
pic_actor4 VARCHAR(200)
);

DROP TABLE Files;
DROP TABLE Movie;
DROP TABLE Review;
DROP TABLE Notice;
DROP TABLE Seat;
DROP TABLE Reservation;
DROP TABLE Customer;
DROP TABLE Comment;
DROP TABLE Multiplex;
DROP TABLE Theater;
DROP TABLE Board;